### PR TITLE
Fix: Add hover state and accessibility to profile icon

### LINKED ISSUE #665: Add Hover State and Accessibility to Profile Icon in Navbar
## Issue Description
The blue profile icon in the navbar (top right) lacks visual feedback and accessibility features. Users have no indication that it's clickable or what happens when clicked.

## Current Behavior
- Profile icon has no hover state
- No tooltip or label explaining what it does
- No visible focus state for keyboard navigation
- Missing ARIA labels for screen readers
- Users are unclear about its purpose

## Expected Behavior
- Show clear hover effect when hovering over the icon
- Display tooltip showing "Profile" or "Account"
- Add focus state for keyboard navigation
- Include proper ARIA labels
- Improve UX by making interactive intent obvious

## Suggested Fix
1. Add Tailwind hover classes: `hover:opacity-80 hover:scale-110 transition`
2. Add tooltip using Radix UI or similar tooltip component
3. Add `focus:outline focus:ring-2` for keyboard navigation
4. Add ARIA labels: `aria-label="User profile menu"`
5. Add title attribute for accessibility

## Implementation Details
```jsx
<button
  aria-label="User profile menu"
  className="hover:opacity-80 hover:scale-110 transition focus:outline-none focus:ring-2 focus:ring-blue-500 rounded-full"
  title="Open profile menu"
>
  <div className="w-10 h-10 bg-blue-500 rounded-full" />
</button>
```

## Files to Check
- Navbar component in apps/platform or main layout
- Check if there's a profile/auth dropdown menu component
- Tailwind configuration for transition classes

## Accessibility Standards
- WCAG 2.1 Level AA compliance
- Keyboard navigation support (Tab key)
- Screen reader support (ARIA labels)

### PR DESCRIPTION
**Pull request by swayam0**
### Summary
Implements hover, focus, and accessibility improvements for the navbar profile icon.

### Changes
- Added hover scale and opacity transitions
- Added keyboard focus ring
- Added `aria-label` and `title` attributes
- Enabled tooltips via shared Page layout

### Verification
- App runs correctly
- Build passes

Closes #665

### CODE REVIEW

**Comment by imsks** [comment]
Hey @swayam0 Thanks for raising the PR. The changes are too many to review. For this PR, it seems like We need few file changes not 31 files. Revisit and apply

**Comment by imsks** [comment]
@NitinGurawaliya Please review

File: packages/components/src/common/Images/UserAvatar.tsx [hunk 1]
```diff
@@ -3,6 +3,7 @@ import { Image, Link } from '@tbe/components';
 import { TOP_NAVIGATION } from '@tbe/constants';
 import { signOut, useSession } from 'next-auth/react';
 import { Fragment } from 'react';
+import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '../../ui/tooltip';
```
Comment (imsks) [inline packages/components/src/common/Images/UserAvatar.tsx]: Always use Absolute imports

**Review by imsks — CHANGES_REQUESTED** [review]

File: packages/components/src/common/Images/UserAvatar.tsx (hunk 1 above)
Comment (swayam0) [reply packages/components/src/common/Images/UserAvatar.tsx]: Thanks for the review 🙏  
I’ve updated the Tooltip imports to use absolute paths as suggested.  
Please let me know if anything else is needed.
